version: '2'
services:
  lib:
    build: .
    command: exit 0
    working_dir: /home/node
    volumes:
      - ./:/home/node
      - ./node_modules:/home/node/node_modules:delegated
    environment:
      - NODE_ENV=$NODE_ENV
      - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
